const data = {
  BD: 'Bangladesh',
  BE: 'Belgium',
  BF: 'Burkina Faso',
  BG: 'Bulgaria',
  BA: 'Bosnia and Herzegovina',
  BB: 'Barbados',
  WF: 'Wallis and Futuna',
  BL: 'Saint Barthelemy',
  BM: 'Bermuda',
  BN: 'Brunei',
  BO: 'Bolivia',
  BH: 'Bahrain',
  BI: 'Burundi',
  BJ: 'Benin',
  BT: 'Bhutan',
  JM: 'Jamaica',
  BV: 'Bouvet Island',
  BW: 'Botswana',
  WS: 'Samoa',
  BQ: 'Bonaire, Saint Eustatius and Saba ',
  BR: 'Brazil',
  BS: 'Bahamas',
  JE: 'Jersey',
  BY: 'Belarus',
  BZ: 'Belize',
  RU: 'Russia',
  RW: 'Rwanda',
  RS: 'Serbia',
  TL: 'East Timor',
  RE: 'Reunion',
  TM: 'Turkmenistan',
  TJ: 'Tajikistan',
  RO: 'Romania',
  TK: 'Tokelau',
  GW: 'Guinea-Bissau',
  GU: 'Guam',
  GT: 'Guatemala',
  GS: 'South Georgia and the South Sandwich Islands',
  GR: 'Greece',
  GQ: 'Equatorial Guinea',
  GP: 'Guadeloupe',
  JP: 'Japan',
  GY: 'Guyana',
  GG: 'Guernsey',
  GF: 'French Guiana',
  GE: 'Georgia',
  GD: 'Grenada',
  GB: 'United Kingdom',
  GA: 'Gabon',
  SV: 'El Salvador',
  GN: 'Guinea',
  GM: 'Gambia',
  GL: 'Greenland',
  GI: 'Gibraltar',
  GH: 'Ghana',
  OM: 'Oman',
  TN: 'Tunisia',
  JO: 'Jordan',
  HR: 'Croatia',
  HT: 'Haiti',
  HU: 'Hungary',
  HK: 'Hong Kong',
  HN: 'Honduras',
  HM: 'Heard Island and McDonald Islands',
  VE: 'Venezuela',
  PR: 'Puerto Rico',
  PS: 'Palestinian Territory',
  PW: 'Palau',
  PT: 'Portugal',
  SJ: 'Svalbard and Jan Mayen',
  PY: 'Paraguay',
  IQ: 'Iraq',
  PA: 'Panama',
  PF: 'French Polynesia',
  PG: 'Papua New Guinea',
  PE: 'Peru',
  PK: 'Pakistan',
  PH: 'Philippines',
  PN: 'Pitcairn',
  PL: 'Poland',
  PM: 'Saint Pierre and Miquelon',
  ZM: 'Zambia',
  EH: 'Western Sahara',
  EE: 'Estonia',
  EG: 'Egypt',
  ZA: 'South Africa',
  EC: 'Ecuador',
  IT: 'Italy',
  VN: 'Vietnam',
  SB: 'Solomon Islands',
  ET: 'Ethiopia',
  SO: 'Somalia',
  ZW: 'Zimbabwe',
  SA: 'Saudi Arabia',
  ES: 'Spain',
  ER: 'Eritrea',
  ME: 'Montenegro',
  MD: 'Moldova',
  MG: 'Madagascar',
  MF: 'Saint Martin',
  MA: 'Morocco',
  MC: 'Monaco',
  UZ: 'Uzbekistan',
  MM: 'Myanmar',
  ML: 'Mali',
  MO: 'Macao',
  MN: 'Mongolia',
  MH: 'Marshall Islands',
  MK: 'Macedonia',
  MU: 'Mauritius',
  MT: 'Malta',
  MW: 'Malawi',
  MV: 'Maldives',
  MQ: 'Martinique',
  MP: 'Northern Mariana Islands',
  MS: 'Montserrat',
  MR: 'Mauritania',
  IM: 'Isle of Man',
  UG: 'Uganda',
  TZ: 'Tanzania',
  MY: 'Malaysia',
  MX: 'Mexico',
  IL: 'Israel',
  FR: 'France',
  IO: 'British Indian Ocean Territory',
  SH: 'Saint Helena',
  FI: 'Finland',
  FJ: 'Fiji',
  FK: 'Falkland Islands',
  FM: 'Micronesia',
  FO: 'Faroe Islands',
  NI: 'Nicaragua',
  NL: 'Netherlands',
  NO: 'Norway',
  NA: 'Namibia',
  VU: 'Vanuatu',
  NC: 'New Caledonia',
  NE: 'Niger',
  NF: 'Norfolk Island',
  NG: 'Nigeria',
  NZ: 'New Zealand',
  NP: 'Nepal',
  NR: 'Nauru',
  NU: 'Niue',
  CK: 'Cook Islands',
  XK: 'Kosovo',
  CI: 'Ivory Coast',
  CH: 'Switzerland',
  CO: 'Colombia',
  CN: 'China',
  CM: 'Cameroon',
  CL: 'Chile',
  CC: 'Cocos Islands',
  CA: 'Canada',
  CG: 'Republic of the Congo',
  CF: 'Central African Republic',
  CD: 'Democratic Republic of the Congo',
  CZ: 'Czech Republic',
  CY: 'Cyprus',
  CX: 'Christmas Island',
  CR: 'Costa Rica',
  CW: 'Curacao',
  CV: 'Cape Verde',
  CU: 'Cuba',
  SZ: 'Swaziland',
  SY: 'Syria',
  SX: 'Sint Maarten',
  KG: 'Kyrgyzstan',
  KE: 'Kenya',
  SS: 'South Sudan',
  SR: 'Suriname',
  KI: 'Kiribati',
  KH: 'Cambodia',
  KN: 'Saint Kitts and Nevis',
  KM: 'Comoros',
  ST: 'Sao Tome and Principe',
  SK: 'Slovakia',
  KR: 'South Korea',
  SI: 'Slovenia',
  KP: 'North Korea',
  KW: 'Kuwait',
  SN: 'Senegal',
  SM: 'San Marino',
  SL: 'Sierra Leone',
  SC: 'Seychelles',
  KZ: 'Kazakhstan',
  KY: 'Cayman Islands',
  SG: 'Singapore',
  SE: 'Sweden',
  SD: 'Sudan',
  DO: 'Dominican Republic',
  DM: 'Dominica',
  DJ: 'Djibouti',
  DK: 'Denmark',
  VG: 'British Virgin Islands',
  DE: 'Germany',
  YE: 'Yemen',
  DZ: 'Algeria',
  US: 'United States',
  UY: 'Uruguay',
  YT: 'Mayotte',
  UM: 'United States Minor Outlying Islands',
  LB: 'Lebanon',
  LC: 'Saint Lucia',
  LA: 'Laos',
  TV: 'Tuvalu',
  TW: 'Taiwan',
  TT: 'Trinidad and Tobago',
  TR: 'Turkey',
  LK: 'Sri Lanka',
  LI: 'Liechtenstein',
  LV: 'Latvia',
  TO: 'Tonga',
  LT: 'Lithuania',
  LU: 'Luxembourg',
  LR: 'Liberia',
  LS: 'Lesotho',
  TH: 'Thailand',
  TF: 'French Southern Territories',
  TG: 'Togo',
  TD: 'Chad',
  TC: 'Turks and Caicos Islands',
  LY: 'Libya',
  VA: 'Vatican',
  VC: 'Saint Vincent and the Grenadines',
  AE: 'United Arab Emirates',
  AD: 'Andorra',
  AG: 'Antigua and Barbuda',
  AF: 'Afghanistan',
  AI: 'Anguilla',
  VI: 'U.S. Virgin Islands',
  IS: 'Iceland',
  IR: 'Iran',
  AM: 'Armenia',
  AL: 'Albania',
  AO: 'Angola',
  AQ: 'Antarctica',
  AS: 'American Samoa',
  AR: 'Argentina',
  AU: 'Australia',
  AT: 'Austria',
  AW: 'Aruba',
  IN: 'India',
  AX: 'Aland Islands',
  AZ: 'Azerbaijan',
  IE: 'Ireland',
  ID: 'Indonesia',
  UA: 'Ukraine',
  QA: 'Qatar',
  MZ: 'Mozambique',
};

const months = {
  en: [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December',
  ],
  ru: [
    'Января',
    'Февраля',
    'Марта',
    'Апреля',
    'Мая',
    'Июня',
    'Июля',
    'Августа',
    'Сентября',
    'Октября',
    'Ноября',
    'Декабря',
  ],
  be: [
    'Студзеня',
    'Лютага',
    'Сакавiка',
    'Красавiка',
    'Мая',
    'Чэрвеня',
    'Лiпеня',
    'Жнiўня',
    'Верасня',
    'Кастрычнiка',
    'Лiстапада',
    'Снежня',
  ],

};

const week = {
  en: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  ru: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
  be: ['Няд', 'Пнд', 'Аўт', 'Сер', 'Чцв', 'Пят', 'Суб'],
};

const weekAll = {
  en: ['Sunday', 'Monday', 'Tuesday', 'Wednsday', 'Thursday', 'Friday', 'Saturday'],
  ru: ['Воскресенье', 'Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота'],
  be: ['Нядзеля', 'Панядзелак', 'Аўторак', 'Серада', 'Чацьвер', 'Пятнiца', 'Субота'],
};

const staticData = {
  en: ['wind', 'm/s', 'feels like', 'humidity', 'Latitude', 'Longitude'],
  ru: ['ветер', 'м/с', 'ощущается как', 'влажность', 'Широта', 'Долгота'],
  be: ['вецер', 'м/с', 'адчуваецца як', 'вiльготнасць', 'Шырата', 'Даўгата'],
};
const placeholder = {
  en: 'Search city',
  ru: 'Найти город',
  be: 'Знайсцi горад',
};

const weatherDescription = {
  200: ['thunderstorm with light rain', 'гроза с небольшим дождем', 'навальніца з невялікім дажджом'],
  201: ['thunderstorm with rain', 'гроза с дождем', 'навальніца з дажджом'],
  202: ['thunderstorm with heavy rain', 'гроза с проливным дождем', 'навальніца з моцным дажджом'],
  210: ['light thunderstorm', 'легкая гроза', 'лёгкая навальніца'],
  211: ['thunderstorm', 'гроза', 'навальніца'],
  212: ['heavy thunderstorm', 'сильная гроза', 'моцная навальніца'],
  221: ['ragged thunderstorm', 'рваная гроза', 'ірваная навальніца'],
  230: ['thunderstorm with light drizzle', 'гроза с легкой моросью', 'навальніца са слабым дожджыкам'],
  231: ['thunderstorm with drizzle', 'гроза с моросящим дождем', 'навальніца з дробным дожджыкам'],
  232: ['thunderstorm with heavy drizzle', 'гроза с сильным моросящим дождем', 'навальніца з моцным дожджыкам'],
  300: ['light intensity drizzle', 'легкая морось', 'лёгкі дождж'],
  301: ['drizzle', 'изморось', 'імжа'],
  302: ['heavy intensity drizzle', 'сильная морось', 'кароткачасовы дождж'],
  310: ['light intensity drizzle rain', 'легкий моросящий дождь', 'кароткачасовы дождж'],
  311: ['drizzle rain', 'моросящий дождь', 'кароткачасовы дождж'],
  312: ['heavy intensity drizzle rain', 'сильный дождь', 'моцны інтэнсіўны дождж'],
  313: ['shower rain and drizzle', 'дождь', 'дождж'],
  314: ['heavy shower rain and drizzle', 'сильный ливень и дождь', 'моцны дождж'],
  321: ['shower drizzle', 'ливень', 'лівень'],
  500: ['light rain', 'легкий дождь', 'невялікі дождж'],
  501: ['moderate rain', 'умеренный дождь', 'дождж умераны'],
  502: ['heavy intensity rain', 'сильный дождь', 'моцны дождж'],
  503: ['very heavy rain', 'очень сильный дождь', 'вельмі моцны дождж'],
  504: ['extreme rain', 'сильный дождь', 'моцны дождж'],
  511: ['freezing rain', 'ледяной дождь', 'ледзяны дождж'],
  520: ['light intensity shower rain', 'легкий дождь', 'невялікі дождж'],
  521: ['shower rain', 'дождь', 'ліўневы дождж'],
  522: ['heavy intensity shower rain', 'сильный дождь', 'моцны інтэнсіўны дождж'],
  531: ['ragged shower rain', 'прорывной дождь', 'прарыўны дождж'],
  600: ['light snow', 'небольшой снег', 'невялікі снег'],
  601: ['Snow', 'Снег', 'Снег'],
  602: ['Heavy snow', 'Снегопад', 'Моцны снег'],
  611: ['Sleet', 'Мокрый снег', 'Мокры снег'],
  612: ['Light shower sleet', 'Легкий мокрый снег', 'Мокры снег'],
  613: ['Shower sleet', 'Мокрый снег', 'Мокры снег'],
  615: ['Light rain and snow', 'Небольшой дождь и снег', 'Невялікі дождж і снег'],
  616: ['Rain and snow', 'Снег с дождём', 'Снег с дажджом'],
  620: ['Light shower snow', 'Легкий дождь со снегом', 'Лёгкі дождж са снегам'],
  621: ['Shower snow', 'Снег', 'Снег'],
  622: ['Heavy shower snow', 'Сильный снегопад', 'Моцны снег'],
  701: ['mist', 'туман', 'туман'],
  711: ['Smoke', 'дым', 'дым'],
  721: ['Haze', 'Мгла', 'смуга'],
  731: ['sand/dust whirls', 'песок/пыль', 'пясок/пыл'],
  741: ['fog', 'густой туман', 'густы туман'],
  751: ['sand', 'песок', 'пясок'],
  761: ['dust', 'пыль', 'пыл'],
  762: ['volcanic ash', 'вулканический пепел', 'вулканічны попел'],
  771: ['squalls', 'шквалистый ветер', 'шквалісты вецер'],
  781: ['tornado', 'торнадо', 'тарнада'],
  800: ['clear sky', 'чистое небо', 'яснае неба'],
  801: ['few clouds', 'малооблачно', 'малавоблачна'],
  802: ['scattered clouds', 'рассеянные облака', 'раскіданыя хмары'],
  803: ['broken clouds', 'облачно', 'воблачна'],
  804: ['overcast clouds', 'пасмурно', 'пахмурна'],
};

export {
  data, months, week, weekAll, staticData, placeholder, weatherDescription,
};
